/* eslint-disable */
// ImageShape class - extracted from imageTool.js
// Depends on globals: svg, shapes, currentShape

import { updateAttachedArrows as updateArrowsForShape } from "../tools/arrowTool.js";
let isDragging = false;
let hoveredFrameImage = null;
function selectImage() {} // stub - image selection handled by imageTool

class ImageShape {
    constructor(element) {
        this.element = element;
        this.shapeName = 'image';
        this.type = 'image';
        this.shapeID = element.shapeID || `image-${String(Date.now()).slice(0, 8)}-${Math.floor(Math.random() * 10000)}`;
        this.isAIGenerated = element.getAttribute('data-ai-generated') === 'true';
        this.aiModel = element.getAttribute('data-ai-model') || null;

        // Frame attachment properties
        this.parentFrame = null;

        // Upload pipeline state
        this.uploadStatus = 'pending'; // 'pending' | 'uploading' | 'done' | 'failed'
        this.uploadAbortController = null;
        this._uploadIndicator = null;

        // Update element attributes
        this.element.setAttribute('type', 'image');
        this.element.shapeID = this.shapeID;

        // Create a group wrapper for the image to work with frames properly
        this.group = document.createElementNS('http://www.w3.org/2000/svg', 'g');
        this.group.setAttribute('id', this.shapeID);

        // Move the image element into the group
        if (this.element.parentNode) {
            this.element.parentNode.removeChild(this.element);
        }
        this.group.appendChild(this.element);
        this._aiBadge = null;
        this._aiBadgeBackground = null;
        this._aiBadgeLabel = null;
        this._aiBadgeObserver = null;
        if (this.isAIGenerated) this.showAIBadge();
        svg.appendChild(this.group);
    }

    showAIBadge() {
        if (this._aiBadge) return;
        const ns = 'http://www.w3.org/2000/svg';
        const badge = document.createElementNS(ns, 'g');
        badge.setAttribute('class', 'ai-image-badge');
        badge.setAttribute('aria-label', 'This is synthetic media generated by AI.');
        badge.style.pointerEvents = 'all';
        badge.style.cursor = 'help';

        const title = document.createElementNS(ns, 'title');
        title.textContent = 'This is synthetic media generated by AI.';
        badge.appendChild(title);

        badge.addEventListener('pointerenter', () => {
            if (typeof window.__showToast === 'function') {
                window.__showToast('This is synthetic media generated by AI.', { duration: 2200 });
            }
        });

        const background = document.createElementNS(ns, 'rect');
        background.setAttribute('width', '32');
        background.setAttribute('height', '18');
        background.setAttribute('rx', '6');
        background.setAttribute('fill', '#7c5ce0');
        background.setAttribute('stroke', 'rgba(255,255,255,0.72)');
        background.setAttribute('stroke-width', '1');
        badge.appendChild(background);

        const label = document.createElementNS(ns, 'text');
        label.textContent = '✦ AI';
        label.setAttribute('x', '16');
        label.setAttribute('y', '12.5');
        label.setAttribute('fill', '#ffffff');
        label.setAttribute('font-family', 'system-ui, sans-serif');
        label.setAttribute('font-size', '9');
        label.setAttribute('font-weight', '700');
        label.setAttribute('text-anchor', 'middle');
        badge.appendChild(label);

        this.group.appendChild(badge);
        this._aiBadge = badge;
        this._aiBadgeBackground = background;
        this._aiBadgeLabel = label;
        this.updateAIBadgePosition();

        if (typeof MutationObserver !== 'undefined') {
            this._aiBadgeObserver = new MutationObserver(() => this.updateAIBadgePosition());
            this._aiBadgeObserver.observe(this.element, {
                attributes: true,
                attributeFilter: ['x', 'y', 'width', 'height', 'transform'],
            });
        }
    }

    updateAIBadgePosition() {
        if (!this._aiBadge) return;
        const imageWidth = Number.isFinite(this.width) ? Math.abs(this.width) : 32;
        const imageHeight = Number.isFinite(this.height) ? Math.abs(this.height) : 18;
        const inset = Math.max(1, Math.min(6, imageWidth * 0.12, imageHeight * 0.12));
        const x = Number.isFinite(this.x) ? this.x + inset : inset;
        const y = Number.isFinite(this.y) ? this.y + inset : inset;
        const availableScale = Math.min(
            1,
            Math.max(0, imageWidth - inset * 2) / 32,
            Math.max(0, imageHeight - inset * 2) / 18,
        );
        const useDot = availableScale <= 0.75;
        let badgeTransform;

        if (useDot) {
            const dotSize = Math.max(2, Math.min(8, imageWidth * 0.28, imageHeight * 0.28));
            this._aiBadge.setAttribute('data-variant', 'dot');
            this._aiBadgeBackground?.setAttribute('width', String(dotSize));
            this._aiBadgeBackground?.setAttribute('height', String(dotSize));
            this._aiBadgeBackground?.setAttribute('rx', String(dotSize / 2));
            this._aiBadgeLabel?.setAttribute('display', 'none');
            badgeTransform = `translate(${x}, ${y})`;
        } else {
            this._aiBadge.setAttribute('data-variant', 'label');
            this._aiBadgeBackground?.setAttribute('width', '32');
            this._aiBadgeBackground?.setAttribute('height', '18');
            this._aiBadgeBackground?.setAttribute('rx', '6');
            this._aiBadgeLabel?.removeAttribute('display');
            badgeTransform = `translate(${x}, ${y}) scale(${availableScale})`;
        }

        this._aiBadge.setAttribute('transform', badgeTransform);
        const imageTransform = this.element.getAttribute('transform');
        if (imageTransform) {
            this._aiBadge.setAttribute('transform', `${imageTransform} ${badgeTransform}`);
        }
    }

    showUploadIndicator() {
        if (this._uploadIndicator) return;
        const g = document.createElementNS('http://www.w3.org/2000/svg', 'g');
        g.setAttribute('class', 'upload-indicator');

        const x = this.x + 6;
        const y = this.y + 6;

        // Background circle
        const bg = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
        bg.setAttribute('cx', x + 10);
        bg.setAttribute('cy', y + 10);
        bg.setAttribute('r', 12);
        bg.setAttribute('fill', 'rgba(0,0,0,0.7)');
        g.appendChild(bg);

        // Caution/loading icon (⚡ style triangle)
        const icon = document.createElementNS('http://www.w3.org/2000/svg', 'polygon');
        icon.setAttribute('points', `${x+10},${y+3} ${x+17},${y+16} ${x+3},${y+16}`);
        icon.setAttribute('fill', 'none');
        icon.setAttribute('stroke', '#FBBF24');
        icon.setAttribute('stroke-width', '1.5');
        icon.setAttribute('stroke-linejoin', 'round');
        g.appendChild(icon);

        // Exclamation mark inside
        const line = document.createElementNS('http://www.w3.org/2000/svg', 'line');
        line.setAttribute('x1', x + 10);
        line.setAttribute('y1', y + 8);
        line.setAttribute('x2', x + 10);
        line.setAttribute('y2', y + 12);
        line.setAttribute('stroke', '#FBBF24');
        line.setAttribute('stroke-width', '1.5');
        line.setAttribute('stroke-linecap', 'round');
        g.appendChild(line);

        const dot = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
        dot.setAttribute('cx', x + 10);
        dot.setAttribute('cy', y + 14.5);
        dot.setAttribute('r', 0.8);
        dot.setAttribute('fill', '#FBBF24');
        g.appendChild(dot);

        // Pulsing animation
        const animate = document.createElementNS('http://www.w3.org/2000/svg', 'animate');
        animate.setAttribute('attributeName', 'opacity');
        animate.setAttribute('values', '1;0.4;1');
        animate.setAttribute('dur', '1.5s');
        animate.setAttribute('repeatCount', 'indefinite');
        g.appendChild(animate);

        // Apply same transform as image (rotation)
        const transform = this.element.getAttribute('transform');
        if (transform) g.setAttribute('transform', transform);

        g.style.pointerEvents = 'none';
        this.group.appendChild(g);
        this._uploadIndicator = g;
    }

    removeUploadIndicator() {
        if (this._uploadIndicator && this._uploadIndicator.parentNode) {
            this._uploadIndicator.parentNode.removeChild(this._uploadIndicator);
        }
        this._uploadIndicator = null;
    }

    updateUploadIndicatorPosition() {
        if (!this._uploadIndicator) return;
        const x = this.x + 6;
        const y = this.y + 6;

        const bg = this._uploadIndicator.querySelector('circle');
        if (bg) { bg.setAttribute('cx', x + 10); bg.setAttribute('cy', y + 10); }

        const icon = this._uploadIndicator.querySelector('polygon');
        if (icon) icon.setAttribute('points', `${x+10},${y+3} ${x+17},${y+16} ${x+3},${y+16}`);

        const line = this._uploadIndicator.querySelector('line');
        if (line) {
            line.setAttribute('x1', x + 10); line.setAttribute('y1', y + 8);
            line.setAttribute('x2', x + 10); line.setAttribute('y2', y + 12);
        }

        const dots = this._uploadIndicator.querySelectorAll('circle');
        if (dots[1]) { dots[1].setAttribute('cx', x + 10); dots[1].setAttribute('cy', y + 14.5); }

        const transform = this.element.getAttribute('transform');
        if (transform) this._uploadIndicator.setAttribute('transform', transform);
    }
    
    // Position and dimension properties for frame compatibility
    get x() {
        return parseFloat(this.element.getAttribute('x'));
    }
    
    set x(value) {
        this.element.setAttribute('x', value);
        this.element.setAttribute('data-shape-x', value);
    }
    
    get y() {
        return parseFloat(this.element.getAttribute('y'));
    }
    
    set y(value) {
        this.element.setAttribute('y', value);
        this.element.setAttribute('data-shape-y', value);
    }
    
    get width() {
        return parseFloat(this.element.getAttribute('width'));
    }
    
    set width(value) {
        this.element.setAttribute('width', value);
        this.element.setAttribute('data-shape-width', value);
    }
    
    get height() {
        return parseFloat(this.element.getAttribute('height'));
    }
    
    set height(value) {
        this.element.setAttribute('height', value);
        this.element.setAttribute('data-shape-height', value);
    }
    
    get rotation() {
        const transform = this.element.getAttribute('transform');
        if (transform) {
            const rotateMatch = transform.match(/rotate\(([^,]+)/);
            if (rotateMatch) {
                return parseFloat(rotateMatch[1]);
            }
        }
        return 0;
    }
    
    set rotation(value) {
        const centerX = this.x + this.width / 2;
        const centerY = this.y + this.height / 2;
        this.element.setAttribute('transform', `rotate(${value}, ${centerX}, ${centerY})`);
        this.element.setAttribute('data-shape-rotation', value);
    }

    move(dx, dy) {
        this.x += dx;
        this.y += dy;

        // Update transform for rotation
        const centerX = this.x + this.width / 2;
        const centerY = this.y + this.height / 2;
        this.element.setAttribute('transform', `rotate(${this.rotation}, ${centerX}, ${centerY})`);

        // Only update frame containment if we're actively dragging the shape itself
        // and not being moved by a parent frame
        if (isDragging && !this.isBeingMovedByFrame) {
            this.updateFrameContainment();
        }

        this.updateAttachedArrows();
    }

    updateAttachedArrows() {
        updateArrowsForShape(this);
    }

    updateFrameContainment() {
        // Don't update if we're being moved by a frame
        if (this.isBeingMovedByFrame) return;
        
        let targetFrame = null;
        
        // Find which frame this shape is over
        if (typeof shapes !== 'undefined' && Array.isArray(shapes)) {
            shapes.forEach(shape => {
                if (shape.shapeName === 'frame' && shape.isShapeInFrame(this)) {
                    targetFrame = shape;
                }
            });
        }
        
        // If we have a parent frame and we're being dragged, temporarily remove clipping
        if (this.parentFrame && isDragging) {
            this.parentFrame.temporarilyRemoveFromFrame(this);
        }
        
        // Update frame highlighting
        if (hoveredFrameImage && hoveredFrameImage !== targetFrame) {
            hoveredFrameImage.removeHighlight();
        }
        
        if (targetFrame && targetFrame !== hoveredFrameImage) {
            targetFrame.highlightFrame();
        }
        
        hoveredFrameImage = targetFrame;
    }

    contains(x, y) {
        const imgX = this.x;
        const imgY = this.y;
        const imgWidth = this.width;
        const imgHeight = this.height;
        
        // Simple bounding box check (could be enhanced for rotation)
        return x >= imgX && x <= imgX + imgWidth && y >= imgY && y <= imgY + imgHeight;
    }

    // Add draw method for consistency with other shapes
    draw() {
        this.updateAIBadgePosition();
    }

    remove() {
        if (this.group?.parentNode) this.group.parentNode.removeChild(this.group);
        if (typeof shapes !== 'undefined' && Array.isArray(shapes)) {
            const index = shapes.indexOf(this);
            if (index !== -1) shapes.splice(index, 1);
        }
    }

    restore() {
        if (svg && this.group && !this.group.parentNode) svg.appendChild(this.group);
        if (typeof shapes !== 'undefined' && Array.isArray(shapes) && !shapes.includes(this)) shapes.push(this);
        this.updateAIBadgePosition();
    }

    // Add methods for frame compatibility
    removeSelection() {
        // Remove selection outlines from SVG
        svg.querySelectorAll(".selection-outline").forEach(el => el.remove());
        // Remove resize/rotation anchors if present
        svg.querySelectorAll(".resize-anchor, .rotation-anchor").forEach(el => el.remove());
    }

    selectShape() {
        // Image interaction state lives in imageTool. Use its bridge so
        // programmatically-created images (graphs, restored scenes, paste)
        // receive the same drag/resize controls as pointer-selected images.
        if (typeof window.__selectImageElement === 'function') {
            window.__selectImageElement(this.element, { force: true });
        }
    }
}

export { ImageShape };
